language: r
cache: packages
warnings_are_errors: true
sudo: required

r_packages:
  - covr
  
r_binary_packages:
  - rjags
   
## test different platforms 
matrix:
  include:  
  - os: linux
    r: devel
  - os: osx
    r: devel
    before_install:
      - curl -O http://r.research.att.com/libs/gfortran-4.8.2-darwin13.tar.bz2
      - sudo tar fvxz gfortran-4.8.2-darwin13.tar.bz2 -C /
      - brew update
      - brew install jags
      - brew install libssh2

##create notifications
notifications:
  email:
    recipients:
      - cb@r-luminescence.de
      - sk@r-luminescence.de
    on_success: change
    on_failure: change

##grep data from testthat
after_success:
- Rscript -e 'covr::codecov()'
