language: r
cache: packages
warnings_are_errors: true
sudo: required

r:
  - devel

os:
  - linux
  - osx:
    - before_install:
      - brew update
      - brew install jags
  
r_packages:
  - covr
  
r_binary_packages:
  - rjags

notifications:
  email:
    recipients:
      - cb@r-luminescence.de
      - sk@r-luminescence.de
    on_success: change
    on_failure: change

after_success:
- Rscript -e 'covr::codecov()'
