language: r
warnings_are_errors: true
sudo: required

os:
  - linux
  - osx
  
r_packages:
  - covr
  
r_binary_packages:
  - rjags

notifications:
  email:
    recipients:
      - cb@r-luminescence.de
      - sk@r-luminescence.de
    on_success: change
    on_failure: change

after_success:
  - bash <(curl -s https://codecov.io/bash)
