language: r
cache: packages
warnings_are_errors: true
sudo: required

r_packages:
  - covr
  
r_binary_packages:
  - rjags
  
# account for requirements of different platforms
matrix:
  include:  
  - os: linux
    r: devel
  - os: osx
    r: devel
    before_install:
      - brew update
      - brew install jags

notifications:
  email:
    recipients:
      - cb@r-luminescence.de
      - sk@r-luminescence.de
    on_success: change
    on_failure: change

after_success:
- Rscript -e 'covr::codecov()'
