language: r
warnings_are_errors: true
sudo: required

os:
  - linux
  - osx

r_binary_packages:
  - rjags

notifications:
  email:
    recipients:
      - cb@r-luminescence.de
      - sk@r-luminescence.de
    on_success: change
    on_failure: change
