language: r
cache: packages
warnings_are_errors: true
sudo: required

apt_packages:
  - jags

r_packages:
  - devtools
  - covr
  - magrittr
  - Rcpp
  - RcppArmadillo
  - bbmle
  - data.table
  - httr
  - matrixStats
  - minpack.lm
  - plotrix
  - raster
  - readxl
  - shape
  - XML
  - zoo
  - RLumShiny
  - RLumModel
  - plotly
  - rmarkdown
  - rstudioapi
  - coda
  - pander
  - testthat
  - R.rsp

## test different platforms
matrix:
  include:
  - os: linux
    r: oldrel
    before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y ghostscript
    env: CACHE_NAME=JOB1
  - os: linux
    r: release
    before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y ghostscript
    env: CACHE_NAME=JOB2
  - os: linux
    r: devel
    before_install:
      - sudo apt-get -qq update
      - sudo apt-get install -y ghostscript
    env: CACHE_NAME=JOB3
  - os: osx
    r: release
    before_install:
      #- sudo rm '/usr/local/include/c++'
      - sudo rm '/usr/local/bin/gfortran'
      - brew install gcc
      - brew install jags
      - brew install libssh2
    env: CACHE_NAME=JOB4

##create notifications
notifications:
  email:
    recipients:
      - cb@r-luminescence.de
      - sk@r-luminescence.de
    on_success: change
    on_failure: change

##grep data from testthat
after_success:
- Rscript -e 'covr::codecov()'
