language: r
warnings_are_errors: true
sudo: required

r_binary _packages:
  - rjags

notifications:
  email:
    recipients:
      - cb@r-luminescence.de
      - sk@r-luminescence.de
    on_success: change
    on_failure: change
