# DO NOT CHANGE the "init" and "install" sections below
# Download script file from GitHub
init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'
install:
  ps: Bootstrap
  
    # fetch prebuilt deps
  - mkdir deps
  
  - nuget install zlib-%tbs_tools%-%tbs_arch%-master -Version 1.2.7.2 -Source https://ci.appveyor.com/nuget/zlib-shallow-x0n34b3pfq1b
  - ps: move zlib*\* deps -force
  - if [%tbs_tools%]==[mingw] move deps\libzlibstatic.a deps\libz.a
  - if [%tbs_tools%]==[msvc12] move deps\zlibstatic.lib deps\zlib.lib
  - SET tbsd_zlib_built=1
  - SET tbsd_zlib_incdir=deps
  - SET tbsd_zlib_libdir=deps

# Adapt as necessary starting from here

build_script:
  - travis-tool.sh install_deps

test_script:
  - travis-tool.sh run_tests

on_failure:
  - travis-tool.sh dump_logs

artifacts:
  - path: '*.Rcheck\**\*.log'
    name: Logs

  - path: '*.Rcheck\**\*.out'
    name: Logs

  - path: '*.Rcheck\**\*.fail'
    name: Logs

  - path: '*.Rcheck\**\*.Rout'
    name: Logs

  - path: '\*_*.tar.gz'
    name: Bits

  - path: '\*_*.zip'
    name: Bits
